import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@anoopqb/simple-ui/dist/index.css";
// import { Header } from "@anoopqb/simple-ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App 1",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch data from the API
  // const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/global?pLevel=8`);
  // const apiData = await response.json();

  // // Extract Header props from the API response
  // const headerProps = {
  //   propertyName: apiData.data.propertyName,
  //   topNavItems: apiData.data.topNavItems,
  //   primaryColor: apiData.data.primaryColor
  // };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <Header {...headerProps} /> */}
        {children}
      </body>
    </html>
  );
}
