import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "@anoopqb/simple-ui/dist/index.css";
import { Header, Footer } from "./components";


// import "./styles/sitea.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Master Template 3",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch data from the API
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/headers?filters[slug]=header&pLevel=8`, {
    headers: {
      'Authorization': `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
      'Content-Type': 'application/json',
    },
  });
  const apiData = await response.json();

  console.log(apiData.data[0].NavMenu)

  // // Extract Header props from the API response
  const headerProps = {
    Logo: apiData.data[0].Logo.url,
    topNavItems: apiData.data[0].NavMenu,
    // primaryColor: apiData.data.primaryColor
  };

  const siteId = process.env.NEXT_PUBLIC_SITE || 'sitea';
  const cssFile = `styles/${siteId}.css`;

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href={`${cssFile}`} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header Logo={`${process.env.NEXT_PUBLIC_IMAGE_URL}${headerProps.Logo}`} topNavItems={headerProps.topNavItems} primaryColor="" />
        {children}
        <Footer
          propertyName="Elite Roofers"
          address={{
            street: "123 Main Street",
            city: "San Francisco",
            state: "CA",
            zipCode: "94102"
          }}
          officeHours={{
            weekdays: "9:00 AM - 6:00 PM",
            saturday: "10:00 AM - 4:00 PM",
            sunday: "Closed"
          }}
          primaryColor=""
          phone="(555) 123-4567"
          email="info@example.com"
        />
      </body>
    </html>
  );
}
